# Generated by Django 2.2.9 on 2020-02-05 06:09

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='VreportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('content', wagtail.core.fields.StreamField([('reports', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=500, required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))])), ('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'village report Page',
                'verbose_name_plural': 'Village Report Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
