# Generated by Django 2.2.10 on 2020-02-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vreportpage',
            options={'verbose_name': 'vreport Page', 'verbose_name_plural': 'Vreport Pages'},
        ),
    ]
