# Generated by Django 2.2.10 on 2020-02-20 07:51

from django.db import migrations, models
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='content',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichtextBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
