# Generated by Django 2.2.10 on 2020-02-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20200220_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='peoplepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='peoplepage',
            name='heading',
        ),
    ]
