# Generated by Django 2.2.9 on 2020-01-31 13:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('content', wagtail.core.fields.StreamField([('doc_upload', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('points', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('point', wagtail.core.blocks.CharBlock(max_length=200, required=True)), ('doc_upload', wagtail.documents.blocks.DocumentChooserBlock(required=True))])))]))], blank=True, null=True)),
                ('contents', wagtail.core.fields.StreamField([('doc', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('doc', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Presentation and Document Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
