# Generated by Django 2.2.10 on 2020-03-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='background',
            new_name='uma_structure',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='history',
        ),
    ]
