# Generated by Django 2.2.10 on 2020-05-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200314_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='participate',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='participate_points',
        ),
    ]
