# Generated by Django 2.2.10 on 2020-05-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200522_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='uma_structure',
        ),
    ]
