# Generated by Django 2.0 on 2020-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20200613_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childreg',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='forms/upload'),
        ),
    ]
