# Generated by Django 2.0 on 2020-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20200614_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childreg',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='forms/upload/'),
        ),
    ]
