# Generated by Django 2.0 on 2020-06-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_auto_20200614_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childreg',
            name='cimage',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
