# Generated by Django 2.2.9 on 2020-02-06 05:40

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.fields
import workshop.dayfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('custom_heading', models.CharField(help_text='Overwrites the default title', max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkshopDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('type_of_workshop', workshop.dayfield.TypesOfWorkshopsField(choices=[('Past', 'Past'), ('Upcoming', 'Upcoming')], max_length=10, null=True)),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
                ('content', wagtail.core.fields.StreamField([('description', streams.blocks.DescriptiveRichtextBlock())], blank=True, null=True)),
                ('date_of_event', models.DateField(null=True)),
                ('time_of_event', models.TimeField(null=True)),
                ('day_of_event', workshop.dayfield.DayOfTheWeekField(choices=[('Friday', 'Friday'), ('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=10, null=True)),
                ('address', models.CharField(max_length=300)),
                ('blog_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
