# Generated by Django 2.2.10 on 2020-05-27 15:34

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('workshop', '0002_auto_20200206_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoplistingpage',
            name='content',
            field=wagtail.core.fields.StreamField([('description', streams.blocks.DescriptiveRichtextBlock())], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WorkshopDetailPage',
        ),
    ]
