# Generated by Django 2.2.10 on 2020-05-27 15:48

from django.db import migrations, models
import django.db.models.deletion
import workshop.dayfield


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('workshop', '0003_auto_20200527_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('type_of_workshop', workshop.dayfield.TypesOfWorkshopsField(choices=[('Past', 'Past'), ('Upcoming', 'Upcoming')], max_length=10, null=True)),
                ('custom_title', models.CharField(help_text='Overwrites the default title', max_length=100)),
                ('short_desc', models.CharField(max_length=100)),
                ('blog_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
