# Generated by Django 2.2.10 on 2020-05-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('workshop', '0004_workshopdetailpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkshopDetailPage',
        ),
    ]
