# Generated by Django 2.2.10 on 2020-06-16 22:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDCPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('contents', wagtail.core.fields.StreamField([('doc', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(icon='image')), ('doc', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TDC Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
