# Generated by Django 2.2.9 on 2020-01-10 10:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(default='Add subtitle'),
        ),
    ]
