# Generated by Django 2.2.9 on 2020-01-10 10:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_banner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='vision_and_mission',
            field=wagtail.core.fields.RichTextField(default='UMA Vision and Mission'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=wagtail.core.fields.RichTextField(default='तकनीकी संस्थाओं का ज्ञान - स्वैच्छिक संगठनों का अनुभव - सरकार के संसाधन सभी को मिलाकर गांवों के विकास के लिए'),
        ),
    ]
