# Generated by Django 2.2.9 on 2020-01-10 12:11

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200110_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='important_links',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
