# Generated by Django 2.2.9 on 2020-01-10 12:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200110_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='workshop_and_events',
            field=wagtail.core.fields.StreamField([('cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))]))]))], blank=True, null=True),
        ),
    ]
