# Generated by Django 2.2.9 on 2020-01-14 08:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_workshop_and_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='vision_and_mission',
            field=wagtail.core.fields.RichTextField(blank=True, default='UMA Vision and Mission', null=True),
        ),
    ]
