# Generated by Django 2.2.10 on 2020-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_applypage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='applypage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
